### ISSUE TITLE
Start, Stop, Start doesn't work

### ISSUE THREAD

**Issue by MeenaAlfons** [pusher/flutter_pusher_beams#12]
Calling stop() correctly deregisters the device. However, calling start again doesn't register the device again. This is a valid use case and we got customer feedback about it for other SDKs (i.e. Android).

**Comment by gardun0** [comment]
Hey @MeenaAlfons, I'll test but what it's the behavior you got?

**Comment by MeenaAlfons** [comment]
This bug got fixed in Beams Android SDK version 1.9.0 two days ago. I think flutter is just a shell around the native SDK. So the solution should be simple by using the latest Android SDK version 1.9.0.
