### ISSUE TITLE
Official Documentation

### ISSUE THREAD

**Issue by gardun0** [pusher/flutter_pusher_beams#7]
- [ ] Getting Started
- [ ] Installation
- [ ] Examples
- [ ] Tutorials
- [ ] User Guides

**Comment by msudgh** [comment]
Hi thanks for your great job i wanted to point out that pub.dev link still uses wrong repo address, please check screenshot
<img width="1920" alt="Screen Shot 2021-12-28 at 13 47 10" src="https://user-images.githubusercontent.com/11756815/147556041-40528e5f-7d36-41f3-95b5-18237591b4f6.png">
